apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: '{{ fromClusterClaim "cluster-name"}}-resource'
  namespace: '{{ fromClusterClaim "cluster-name"}}-catalog'
spec:
  sourceType: grpc
  image: 'sandbox.opentlc.com/example/catalog-for-{{ fromClusterClaim "cluster-name"}}:tag'
  displayName: Plain operator catalog
  publisher: grpc
  updateStrategy:
    registryPoll: 
      interval: 30m