apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: base-appsets-deploy
  namespace: multicloud-gitops-hub
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          base-appsets: deploy