apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: base-appsets-true
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          base-appsets: "true"