apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: rhacm-manifests
  namespace: config-policies
  annotations:
    apps.open-cluster-management.io/git-path: rhacm-manifests
    apps.open-cluster-management.io/git-branch: main
spec:
  channel: config-policies/vadim-channel
  placement:
    local: "true"