apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedClusterSetBinding
metadata:
  name: default
#  namespace: multicloud-gitops-hub
  namespace: openshift-gitops
spec:
  clusterSet: default