apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: config-policies-prod-manifests
  namespace: config-policies
  labels: 
    rhacm-app: config-policies-manifests
  annotations:
    apps.open-cluster-management.io/git-path: /
    apps.open-cluster-management.io/git-branch: prod
spec:
  channel: config-policies/vadim-channel
  placement:
    clusters:
      - name: local-cluster
  packageOverrides:
    - packageName: kustomization
      packageOverrides: 
        - value: |
            generators:
              - config-policies-prod/base-configuration.yaml
              - config-policies-prod/optional-configuration.yaml