apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: plain-resource
  namespace: plain-catalog
spec:
  sourceType: grpc
  image: sandbox.opentlc.com/example/plain-catalog-production-image:tag 
  displayName: Plain operator catalog
  publisher: grpc
  updateStrategy:
    registryPoll: 
      interval: 30m