apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: plain-catalog
  annotations:
    test/annotation: test
stringData:
  config.yaml: |  
    global:
      resolve_timeout: 5m
    receivers:
      - name: cool
        webhook_configs:
          - url: "tt.com"
            send_resolved: true
            http_config:
              test_auth:
                username: '{{ fromSecret "kube-system" "aws-creds" "aws_access_key_id" }}'
                password: '{{ fromSecret "kube-system" "aws-creds" "aws_access_key_id" }}'
      - name: notcool
        webhook_configs:
          - url: "ttt.com"
            send_resolved: true
            http_config:
              test_auth:
                username: '{{ fromSecret "kube-system" "aws-creds" "aws_access_key_id" }}'
                password: '{{ fromSecret "kube-system" "aws-creds" "aws_access_key_id" }}'
      - name: null-receiver
    route:
      group_by:
        - namespace:
      group_interval: 1m
      group_wait: 30s
      receiver: null-receiver
      repeat_interval: 30m
      routes:
        - receiver: "cool"
          match_re:
            dbname: .+
