apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: plain-catalog
stringData:
  config.yml: |  
    global:
      resolve_timeout: 5m
    receivers:
      - name: cool
        text: notcool
      - name: notcool
        text: cool
    db:
      routes:
        - receiver: "cool"
          match_re:
            dbname: .+
