apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: plain-catalog
stringData:
  config.yml: |  
    global:
      resolve_timeout: 5m
    receivers:
      - name: cool
        text: '{{ fromConfigMap "admin-ns" "console-notification" (fromClusterClaim "base-config") }} OpenShift version {{ fromClusterClaim "version.openshift.io" }}. The name of the cluster in RHACM is {{ fromSecret "open-cluster-management-agent" "hub-kubeconfig-secret" "cluster-name" | base64dec }}'
      - name: notcool
        text: cool
    db:
      routes:
        - receiver: "cool"
          match_re:
            dbname: .+
